# Generated by Django 4.0.6 on 2022-07-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('month', models.DateTimeField()),
                ('pay_address', models.CharField(max_length=255)),
                ('use_class', models.CharField(max_length=255)),
                ('purchasing_channel', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('amount', models.FloatField()),
                ('invoice_calss', models.CharField(max_length=255)),
                ('expenses_claim', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=255)),
                ('financial_payment', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=255)),
            ],
        ),
    ]
