# Generated by Django 4.0.6 on 2022-07-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='month',
            field=models.IntegerField(max_length=255),
        ),
    ]
