# Generated by Django 4.0.6 on 2022-07-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_alter_cmdb_date_alter_cmdb_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmdb',
            old_name='detail',
            new_name='明细',
        ),
        migrations.RenameField(
            model_name='cmdb',
            old_name='amount',
            new_name='金额',
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='expenses_claim',
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='financial_payment',
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='invoice_calss',
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='month',
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='pay_address',
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='purchasing_channel',
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='use_class',
        ),
        migrations.AddField(
            model_name='cmdb',
            name='发票类型',
            field=models.CharField(blank=True, choices=[('screenshot', '截图'), ('bill', '发票'), ('all', '截图+发票')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='小类别',
            field=models.CharField(blank=True, choices=[('card', '名片印制'), ('daily office', '日常办公'), ('Employee Benefits', '员工福利')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='报销申请',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='日期',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='月份',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='花费地',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='财务打款',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='购买渠道',
            field=models.CharField(blank=True, choices=[('jingdong', '京东'), ('taobao', '淘宝'), ('pinduoduo', '拼多多'), ('shansong', '闪送')], max_length=255, null=True),
        ),
    ]
