# Generated by Django 4.0.6 on 2022-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0004_alter_cmdb_发票类型'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='小类别',
            field=models.CharField(blank=True, choices=[('名片印制', '名片印制'), ('日常办公', '日常办公'), ('员工福利', '员工福利')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='购买渠道',
            field=models.CharField(blank=True, choices=[('京东', '京东'), ('淘宝', '淘宝'), ('拼多多', '拼多多'), ('闪送', '闪送')], max_length=255, null=True),
        ),
    ]
