# Generated by Django 4.0.6 on 2022-07-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0005_alter_cmdb_小类别_alter_cmdb_购买渠道'),
    ]

    operations = [
        migrations.CreateModel(
            name='fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('日期', models.DateField(blank=True, null=True)),
                ('明细', models.TextField()),
                ('金额', models.FloatField()),
            ],
        ),
    ]
