# Generated by Django 4.0.6 on 2022-07-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0006_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='back_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('日期', models.DateField(blank=True, null=True)),
                ('入账', models.FloatField()),
            ],
        ),
    ]
